// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPI1G6Py2pz79oLOn0WqMr6U69dyYEeMs',
    appId: '1:434678388315:web:0ef06a3d3e85bd66a6517e',
    messagingSenderId: '434678388315',
    projectId: 'greenlife-f2d2c',
    authDomain: 'greenlife-f2d2c.firebaseapp.com',
    storageBucket: 'greenlife-f2d2c.firebasestorage.app',
    measurementId: 'G-GF6VD7Z8XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDhEPsbuZm6upxCJdk3CbVZ33mFYs_Qak',
    appId: '1:434678388315:android:6b609333a525e685a6517e',
    messagingSenderId: '434678388315',
    projectId: 'greenlife-f2d2c',
    storageBucket: 'greenlife-f2d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhhrH_cvmxqpITL1VRYW_uan_7UrrIC0',
    appId: '1:434678388315:ios:08eb9caf79c48403a6517e',
    messagingSenderId: '434678388315',
    projectId: 'greenlife-f2d2c',
    storageBucket: 'greenlife-f2d2c.firebasestorage.app',
    iosBundleId: 'com.brand.greenlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhhrH_cvmxqpITL1VRYW_uan_7UrrIC0',
    appId: '1:434678388315:ios:08eb9caf79c48403a6517e',
    messagingSenderId: '434678388315',
    projectId: 'greenlife-f2d2c',
    storageBucket: 'greenlife-f2d2c.firebasestorage.app',
    iosBundleId: 'com.brand.greenlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPI1G6Py2pz79oLOn0WqMr6U69dyYEeMs',
    appId: '1:434678388315:web:25731d1a32056b9ba6517e',
    messagingSenderId: '434678388315',
    projectId: 'greenlife-f2d2c',
    authDomain: 'greenlife-f2d2c.firebaseapp.com',
    storageBucket: 'greenlife-f2d2c.firebasestorage.app',
    measurementId: 'G-9THB9B6MRQ',
  );
}
